name: flutter_hive_tdo
description: Flutter Hive Todo app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  uuid: ^3.0.5
  intl: ^0.17.0
  flutter_datetime_picker: ^1.5.1
  animate_do: ^2.1.0
  flutter_beautiful_popup: ^1.7.0
  panara_dialogs: ^0.1.2
  lottie: ^1.4.0
  ftoast: ^2.0.0
  flutter_slider_drawer: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.0.1
  hive_generator: 1.1.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/lottie/
  

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
